---
abstract: 'examination and modification of subroutines'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  ExtUtils::CBuilder: 0.15
  Module::Build: 0
  Test::More: 0
  perl: 5.008
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.008
  strict: 0
  warnings: 0
dynamic_config: 0
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Mutate
provides:
  Sub::Mutate:
    file: lib/Sub/Mutate.pm
    version: 0.005
requires:
  Exporter: 0
  XSLoader: 0
  parent: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.005
