---
name: Sub-Mutate
version: 0.001
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
abstract: examination and modification of subroutines
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  XSLoader: 0
  parent: 0
  perl: 5.008
  strict: 0
  warnings: 0
build_requires:
  ExtUtils::CBuilder: 0.15
  Module::Build: 0
  Test::More: 0
  perl: 5.008
  strict: 0
  warnings: 0
dynamic_config: 0
provides:
  Sub::Mutate:
    file: lib/Sub/Mutate.pm
    version: 0.001
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: module
